import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "yaml";
const schema = parse(readFileSync("semconv/code_artifact.yaml", "utf8"));
const text =
  "// Generated by scripts/generate-semconv.mjs; do not edit.\n" +
  schema.groups
    .flatMap((g) => g.attributes)
    .map(
      (a) =>
        `export const ${a.id.replace("code_artifact.", "").replaceAll(".", "_").toUpperCase()} = '${a.id}';`,
    )
    .join("\n") +
  "\n";
const { format } = await import("prettier");
const formatted = await format(text, { parser: "typescript" });
if (process.argv.includes("--check")) {
  if (readFileSync("src/semconv.ts", "utf8") !== formatted)
    throw new Error("Run node scripts/generate-semconv.mjs");
} else writeFileSync("src/semconv.ts", formatted);
