// Generated by scripts/generate-semconv.mjs; do not edit.
export const SCHEMA_VERSION = "code_artifact.schema.version";
export const FUNCTION = "code_artifact.function";
export const GENERATOR = "code_artifact.generator";
export const INTENT_HASH = "code_artifact.intent.hash";
export const ASSUMPTIONS_HASH = "code_artifact.assumptions.hash";
export const CHECK_IDS = "code_artifact.check.ids";
export const CHECK_CONTRACT_HASHES = "code_artifact.check.contract_hashes";
export const CHECK_SAMPLE_RATES = "code_artifact.check.sample_rates";
export const CHECK_RESULTS = "code_artifact.check.results";
